<a href="https://colab.research.google.com/github/AbdulQadir8/Digit_mnist_with_cnn/blob/master/Digit_mnist_with_cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Mnist digit classification with Convolution Neural Network***
(first network build by myself)

In [2]:
from keras import models
from keras import layers

In [3]:
from keras.utils import to_categorical

In [4]:
from keras.datasets import mnist

In [5]:
(train_data,train_labels),(test_data,test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [6]:
train_data.shape

(60000, 28, 28)

In [7]:
test_data.shape

(10000, 28, 28)

In [8]:
train_labels.shape

(60000,)

In [9]:
test_labels.shape

(10000,)

In [10]:
train_data[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [11]:
train_data = train_data.reshape(60000,28,28,1)
train_data = train_data.astype('float32')/255

In [12]:
test_data = test_data.reshape(10000,28,28,1)
test_data = test_data.astype('float32')/255

In [13]:
train_data[0]

array([[[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        

In [14]:
train_labels[0]

5

In [15]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [16]:
test_labels[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [17]:
model = models.Sequential()
model.add(layers.Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64,(3,3),activation='relu'))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64,(3,3),activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64,activation='relu'))
model.add(layers.Dense(10,activation='softmax'))


In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 3, 3, 64)          36928     
                                                                 
 flatten (Flatten)           (None, 576)               0

In [20]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_data,train_labels,epochs=5,batch_size=64)

Epoch 1/5
938/938 [==============================] - 55s 57ms/step - loss: 0.1798 - accuracy: 0.9430
Epoch 2/5
938/938 [==============================] - 53s 56ms/step - loss: 0.0483 - accuracy: 0.9848
Epoch 3/5
938/938 [==============================] - 52s 56ms/step - loss: 0.0334 - accuracy: 0.9898
Epoch 4/5
938/938 [==============================] - 52s 56ms/step - loss: 0.0248 - accuracy: 0.9921
Epoch 5/5
938/938 [==============================] - 52s 56ms/step - loss: 0.0202 - accuracy: 0.9935


In [23]:
# Lets evaluate the model on test data
test_loss,test_acc = model.evaluate(test_data,test_labels)
test_acc

313/313 [==============================] - 3s 11ms/step - loss: 0.0438 - accuracy: 0.9865


0.9865000247955322